# Generated by Django 2.2.5 on 2019-09-24 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('ISBN', models.CharField(max_length=64)),
                ('fecha', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('contrasena', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duenoReview', to='App01.usuarios')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tituloLibro', to='App01.libros')),
            ],
        ),
    ]
